## GET All Todos
GET  http://localhost:8000/api/todo HTTP/1.1

### 

##Add a new Todo
POST http://localhost:8000/api/todo HTTP/1.1
Content-Type: application/json

{
	"title": "Zoom Meeting",
	"description": "Attend the board meeting by 4pm"
}

###

## Get a Todo by ID
GET http://localhost:8000/api/todo/63720d940569518856dd01f3 HTTP/1.1

###

## Update a Todo
PUT http://localhost:8000/api/todo/63720d940569518856dd01f3 HTTP/1.1
Content-Type: application/json

{
	"title": "Google Meet board meeting",
	"description": "Attend the board meeting by 8pm"
}

###

## Delete a Todo
DELETE http://localhost:8000/api/todo/63720d940569518856dd01f3 HTTP/1.1